version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      DJANGO_ALLOWED_HOSTS: backend,localhost,127.0.0.1
      DJANGO_DEBUG: "false"
      DJANGO_SECRET_KEY: change-me
      MATCH_CACHE_SECONDS: "300"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/health/')\""]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
