# Generated by Django 5.2.6 on 2025-09-22 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='ondebola', max_length=32)),
                ('date_text', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.CharField(blank=True, max_length=16, null=True)),
                ('home', models.CharField(blank=True, max_length=128, null=True)),
                ('away', models.CharField(blank=True, max_length=128, null=True)),
                ('competition', models.CharField(blank=True, max_length=128, null=True)),
                ('channels', models.JSONField(default=list)),
                ('raw', models.TextField()),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'fetched_at'], name='matches_mat_source_39d036_idx')],
            },
        ),
    ]
